name: 'Set env vars'
description: 'Set environment variables'

runs:
  using: 'composite'
  steps:
    - name: Set env vars
      shell: sh
      run: |
        # Convert REPO_OWNER to lowercase manually
        REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
        
        # Extract repository name and convert to lowercase
        REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
        
        # Extract tag from ref
        TAG=$(echo "${GITHUB_REF#refs/tags/}")
        echo "TAG=${TAG}" >> $GITHUB_ENV
