name: 'Send Slack Notofication'
description: 'Send Slack Notofication'
inputs:
  scan_type:
    description: "Scan Type"
    required: true
  docker_image:
    description: "Docker image"
    required: false


runs:
  using: 'composite'
  steps:
    - name: Run Trivy vulnerability scanner
      if: ${{ inputs.scan_type == 'image' }}
      shell: bash
      run: docker run --rm -v ${{ github.workspace }}:/output aquasec/trivy:0.54.1 image --scanners vuln,secret --format cyclonedx --output /output/trivy_dt_api ${{ inputs.docker_image }}
    - name: Upload Artifact - Scan result
      uses: actions/upload-artifact@v4
      with:
        name: trivy_dt_api
        path: /${{ github.workspace }}/trivy_dt_api
        retention-days: 5
        compression-level: 9
