name: 'Deploy Container to Azure Web APP'
description: 'Deploy Container to Azure Web APP'
inputs:
  webapp_name:
    description: "Web APP name"
    required: true
  docker_image:
    description: "Docker Image"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.webapp_name }}
        images: ${{ inputs.docker_image }}
