name: 'Login to Azure Cloud'
description: 'Login to Azure Cloud'
inputs:
  azure_credentials:
    description: "Azure Credentials"
    required: true


runs:
  using: 'composite'
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}
